/* eslint-disable @next/next/no-page-custom-font */
// eslint-disable-next-line @next/next/no-page-custom-font
import type { Metadata } from "next";
import "./globals.css";
import Header from "document/components/header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap"
          rel="stylesheet"
        />
        <div className="overlay"></div>
        <Header />
        {children}
      </body>
    </html>
  );
}
